y_raiso_cas_auth:
    server_login_url: https://ent.uca.fr/cas/
    server_validation_url: https://ent.uca.fr/cas/serviceValidate
    server_logout_url: https://ent.uca.fr/cas/logout
    xml_namespace: cas
    options: [] # you can add request options (or override global ones) (cf https://symfony.com/doc/current/http_client.html#making-requests)